services:
  db:
    image: postgres:16
    container_name: postgres-clinica
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres    
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server-app:      
    build: 
      context: .
      dockerfile: Server-module/Dockerfile
    container_name: server-clinica
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080" 
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/postgres 
    stdin_open: true 
    tty: true        
    restart: always

volumes:
  postgres_data:
  
